### ISSUE TITLE
Replacement version for support the TestLink 1.9.8

### ISSUE THREAD

**Issue by FLYLEE99** [chusiang/testlink.ansible.role#10]
Hello, I want to use testlink1.9.8. Need to change those places.
I hope to get your answer, thank you.

**Comment by chusiang** [comment]
Hi @FLYLEE99 ,

You can replace some variables like  `testlink_tarball` for use the different edition.

> https://github.com/chusiang/testlink.ansible.role/blob/master/defaults/main.yml#L7

```
testlink_tarball_version: '1.9.17'
testlink_tarball_url: 'https://downloads.sourceforge.net/project/testlink/TestLink%201.9/TestLink%201.9.17/testlink-1.9.17.tar.gz'
testlink_tarball_md5: '7183c30133fecc18c8074142016b6a44'
```

## Example

```
$ vim testlink.yml
---
- name: "setup testlink.yml"
  hosts: all

  roles:
    - {
        role: "chusiang.testlink",
        testlink_tarball_version: "1.9.8",
        testlink_tarball_url: "https://downloads.sourceforge.net/project/testlink/TestLink%201.9/TestLink%201.9.8/testlink-1.9.8.tar.gz",
        testlink_tarball_md5: 'bcfa9c830b6a7cb5f0b9d41ebb6d8d20'
      }
```

By the way, **you need review the requirements** like `mysql-server-5.6` for TestLink 1.9.8, because my only testing on TestLink 1.9.15 and 1.9.17.

Thank you for use this Ansible Role.

## Reference

* https://github.com/chusiang/automate-with-ansible/blob/master/24.how-to-setup-testlink-with-roles.md
* https://chusiang.gitbooks.io/automate-with-ansible/content/24.how-to-setup-testlink-with-roles.html

**Comment by FLYLEE99** [comment]
[testlinklog.txt](https://github.com/chusiang/testlink.ansible.role/files/2033602/testlinklog.txt)
@chusiang Thank you very much for your reply. I'm a beginner.

But after I modified testlink.yml, I implemented docker build in Ubuntu16 in builds. Fail to succeed. The tips are as follows: (the complete process is in the appendix)

```
 [WARNING]: Consider using the get_url or uri module rather than running curl.
If you need to use command because get_url or uri is insufficient you can add
warn=False to this command task or set command_warnings=False in ansible.cfg to
get rid of this message.
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "curl -s http://localhost/login.php | grep title", "delta": "0:00:00.133229", "end": "2018-05-24 01:35:51.235574", "msg": "non-zero return code", "rc": 1, "start": "2018-05-24 01:35:51.102345", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/tmp/testlink.ansible.role/setup.retry

PLAY RECAP *********************************************************************
localhost                  : ok=96   changed=42   unreachable=0    failed=1

The command '/bin/sh -c echo "===> Run playbook ..."                                            &&       ansible-playbook-wrapper' returned a non-zero code: 2
```

Excuse me, please excuse me. I take the liberty to ask,, can you help me create a TestLink1.9.8 docker image?
Thank you again.

**Comment by chusiang** [comment]
Hi @FLYLEE99，

I will be able to build it as soon as possible after two weeks, because I have been busy with speeches in the past two weeks.

**Comment by FLYLEE99** [comment]
@chusiang Oh, I'm sorry to disturb you. If you don't have time, I'll learn by myself

**Comment by chusiang** [comment]
Hi @FLYLEE99 ,

I try to use this playbooks to setup the TestLink 1.9.8 on Vagrant, but the PHP 7.0 is not support TestLink v1.9.8, maybe you can write a new playbooks to do this.

Suggest:

1. **L**: Ubuntu 14.04
1. **A/N**: Apache or Nginx.
1. **M**: MySQL Server 5.5
1. **P**: PHP 5.5

Good luck.


Chu-Siang Lai
Thu May 24 22:40:53 CST 2018

----

# Try on Vagrant 2.1.1 x macOS 10.13.4

## Failed on Ubuntu 16.04 x TestLink v1.9.8

1. Playbooks.

    ```
    TASK [create testlink table and data] ******************************************
    failed: [ubuntu1604] (item=/usr/share/nginx/testlink/install/sql/mysql/testlink_create_tables.sql) => {"changed": false, "item": "/usr/share/nginx/testlink/install/sql/mysql/testlink_create_tables.sql", "msg": "ERROR 1050 (42S01) at line 44: Table 'assignment_types' already exists\n"}
    failed: [ubuntu1604] (item=/usr/share/nginx/testlink/install/sql/mysql/testlink_create_default_data.sql) => {"changed": false, "item": "/usr/share/nginx/testlink/install/sql/mysql/testlink_create_default_data.sql", "msg": "ERROR 1146 (42S02) at line 9: Table 'testlinkdb.db_version' doesn't exist\n"}
    ...ignoring
    ...
    ```

1. Manual import with mysql command.

    ```
    vagrant@ubuntu1604:~$ mysql -u testlinkdb -p testlinkdb < /usr/share/nginx/testlink/install/sql/mysql/testlink_create_tables.sql
    Enter password:
    ERROR 1067 (42000) at line 59: Invalid default value for 'date_added'
    ```

    > This SQL script is not support MySQL v5.7.

## Failed on Ubuntu 14.04 x TestLink v1.9.8

```
vagrant@ubuntu1404:~$ mysql --version
mysql  Ver 14.14 Distrib 5.5.60, for debian-linux-gnu (x86_64) using readline 6.3
```

### Call to undefined function mysql_connect()

Replace the `mysql_connect()` function to `mysqli_connect()`.

```
$ sudo sed -i 's/mysql_connect(/mysqli_connect(/' install/installUtils.php
$ sudo sed -i 's/mysql_connect(/mysqli_connect(/' third_party/adodb/drivers/adodb-mysql.inc.php
$ sudo sed -i 's/mysql_connect(/mysqli_connect(/' third_party/adodb/docs/tute.htm
$ sudo sed -i 's/mysql_connect(/mysqli_connect(/' third_party/phpmailer/examples/test_db_smtp_basic.php
$ sudo sed -i 's/mysql_connect(/mysqli_connect(/' third_party/phpmailer/docs/extending.htm
```

### Call to undefined function mysql_error()

The PHP 7.0 is not support the `mysql_error()` function, so I stop keep going.
